### ISSUE TITLE
I cannot register tool in my app

### ISSUE THREAD

**Issue by dtokarczyk** [hon2a/cypress-antd#2]
I have tried to add helpers to my app but I have some issues.

Steps to reproduce

0. I have an app built on https://github.com/react-boilerplate/react-boilerplate
1. I added a package into my app via `npm i @hon2a/cypress-antd --save-dev`,
2. I added `import '@hon2a/cypress-antd/lib/register` into my custom commands,
3. I tried to use one of the helpers 
4. I have run my e2e tests

While I running the app with imported helpers I'm getting an error 

```
Error: Webpack Compilation Error
./node_modules/@hon2a/cypress-antd/lib/form.js
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js-stable/instance/concat' in '/Users/damiantokarczyk/Development/x/quse/quse-web/node_modules/@hon2a/cypress-antd/lib'
resolve '@babel/runtime-corejs3/core-js-stable/instance/concat' in '/Users/damiantokarczyk/Development/x/quse/quse-web/node_modules/@hon2a/cypress-antd/lib'
```

Thanks for help!

**Comment by hon2a** [comment]
@dtokarczyk Hi, sorry I missed the message. Looks like a missing `@babel/runtime-corejs3`. I'll add it to dependencies; in the meantime, you might fix the issue by adding it to yours.
